# 生命游戏

这是个模拟生命演化的游戏，在一个广阔的生存空间里，设定生命群落存活和繁衍的规则，个体和群落依据既相互竞争又相互依存的法则进行进化。

## 总的规则

- 过于拥挤的分布 - 资源争夺 - 死亡
- 过于孤立的分布 - 不具备种群优势 - 灭绝
- 适度的分布 - 繁衍

## 规则细节

### 规则
#### 对于“填充”的空间：
- 每个有一个或没有邻居的小区都会死亡，就像孤独一样。
- 每个有四个或更多邻居的小区都会死亡，好像是人口过剩。
- 每个有两个或三个邻居的细胞存活下来。

#### 对于“空”或“未填充”的空间
- 每个具有三个邻居的小区变为填充。


- 少于2邻居，死
- 多于3邻居，死
- 正好3邻居，生

## 创作者的解释

- [跳到1分钟处观看规则](http://bazhou.blob.core.windows.net/learning/mpp/414_Does_John_Conway_hate_his_Game_of_Life-E8kUJL04ELA.mp4 )

- [对于这个想法的来源（冯.诺伊曼）可以看这个视频](http://bazhou.blob.core.windows.net/learning/mpp/665_Inventing_Game_of_Life_-_Numberphile-R9Plq-D1gEk.mp4 )

## 交互体验

这个交互体验的目的是获得感官印象

- [体验游戏的过程是没有交互的](https://bitstorm.org/gameoflife/)，

## Wikipedia解释

如果已经明白规则，可以忽略这部分文档。

- [English version long](http://bazhou.blob.core.windows.net/learning/mpp/game_of_life_en.pdf)
- [汉语版本（短）](http://bazhou.blob.core.windows.net/learning/mpp/game_of_life_cn.pdf)

# 挑战

- 用Python实现游戏规则
  - 在1000x1000共一百万个单元里模拟
  - 边界为0
  - 不需要画图，只需要完成进化矩阵的运算即可
- 尽量短的代码
- 尽量高效

# 可以跳过下面全部的参考直接解决问题

## 参考一

[github搜索一个解](https://github.com/domoritz/gameoflife-python)

## 参考二

[Peter Norvig 的 notebook](https://nbviewer.jupyter.org/url/norvig.com/ipython/Life.ipynb)

## 参考三

[这个编程问题的96种语言实现](https://rosettacode.org/wiki/Conway%27s_Game_of_Life)

## 参考四

下面的代码是启发解，虽然不是最优解，但是

- 给出了算法的基本结构
  - 计算邻居数
  - 根据法则进化
- 循环结构指示了计算规模

In [47]:
import random as random
import timeit

# 产生一个百万0，1数组，0代表空（死），1代表生
Z = [[random.choice([0,1]) for x in range(1000)] for y in range(1000)]

print(len(Z),":",len(Z[0]))
# 计算八个邻居数目
def neighbours(Z):
    s = len(Z), len(Z[0])
    
    # 一个初始全为0的邻居数量矩阵
    N = [[0,]*(s[0]) for i in range(s[1])]
    for x in range(1, s[0]-1):                                  # 注意边界
        for y in range(1, s[1]-1):
            N[x][y] = (Z[x-1][y-1] + Z[x][y-1] + Z[x+1][y-1] +  # 邻居数量=周围8个格子生命统计
                       Z[x-1][y]               + Z[x+1][y]   +
                       Z[x-1][y+1] + Z[x][y+1] + Z[x+1][y+1])
    return N

# 根据周围邻居总数应用规则
def evolve(Z):
    s = len(Z), len(Z[0])
    N = neighbours(Z)
    for x in range(1, s[0]-1):
        for y in range(1, s[1]-1):
            if Z[x][y] == 1 and (N[x][y] < 2 or N[x][y] > 3): # 灭亡规则
                Z[x][y] = 0
            elif Z[x][y] == 0 and N[x][y] == 3:               # 繁衍规则
                Z[x][y] = 1
    return Z

print(timeit.timeit(lambda: evolve(Z), number=3))             # 对百万人口作三代进化，统计运算效率

1000 : 1000
5.959602000000814


## 尝试用Numpy解

In [12]:
import timeit
import numpy as np

Znp = np.random.randint(2, size=(1000,1000))
#print(Znp)
def nextGeneration(Z):
    neighborCount = sum(np.roll(np.roll(Z, i, 0), j, 1) for i in (-1, 0, 1) for j in (-1, 0, 1) if (i != 0 or j != 0))
    #return (neighborCount == 3) | ((neighborCount == 1) & (neighborCount == 2)).astype("int8")
    return (neighborCount == 3) | ((neighborCount == 1) & (neighborCount == 2))

def np_solver(Z):  
    #Z = np.argwhere(nextGeneration(Z))#下一代
    Z = np.where(nextGeneration(Z),1,0)#下一代
    return Z # 把实现填进来
    
print(timeit.timeit(lambda: np_solver(Znp), number=100))

8.39200720000008


In [11]:
t = np.random.randint(2, size=(10,10))
print(nextGeneration(t))

[[0 1 1 0 0 1 0 1 1 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 1 1 0 1 0 1 0 1 1]
 [0 0 1 1 1 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]]


## 提示一

- 使用索引[1:-1,1:-1]可以消去邻居数循环

## 提示二

- [argwhere可以帮助作规则判断](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argwhere.html)

## 提示三

-[ravel是view](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ravel.html)

-[参考曾佑轩分享的关于Numpy性能的文章](https://zhuanlan.zhihu.com/p/28626431)

-[numpy.take](https://docs.scipy.org/doc/numpy/reference/generated/numpy.take.html)

-[numpy.compress](https://docs.scipy.org/doc/numpy/reference/generated/numpy.compress.html)